spring:
  application:
    name: bank
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

# security:
#   user:
#     name: eazybytes
#     password: '12345'