spring:
  application:
    name: bank
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

server:
  port: 8081
  servlet:
    session:
      timeout: 20m

jwt:
  secret:
    value: ${JWT_SECRET_VALUE:jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4}
    defaultValue: ${JWT_SECRET_DEFAULT:jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4}
    expiration: ${JWT_SECRET_EXPIRATION:60000}